# Generated by Django 5.1.7 on 2025-03-26 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('id_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('numcard', models.CharField(max_length=19)),
                ('titcard', models.CharField(max_length=255)),
                ('expirycard', models.CharField(max_length=7)),
                ('securycard', models.CharField(max_length=4)),
            ],
        ),
    ]
