# Generated by Django 5.1.7 on 2025-03-26 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_cadastrar', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('numcard', models.CharField(max_length=16)),
                ('titcard', models.CharField(max_length=255)),
                ('expirycard', models.CharField(max_length=7)),
                ('securycard', models.CharField(max_length=4)),
            ],
        ),
        migrations.DeleteModel(
            name='Usuarios',
        ),
    ]
