# Generated by Django 5.1.7 on 2025-03-26 02:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_cadastrar', '0002_usuario_delete_usuarios'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='expirycard',
        ),
    ]
