# Generated by Django 5.1.7 on 2025-03-27 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_cadastrar', '0003_remove_usuario_expirycard'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='expiry_date',
            field=models.CharField(default=2, max_length=7),
            preserve_default=False,
        ),
    ]
